### ISSUE TITLE
Crash on Adding Account 

### ISSUE THREAD

**Issue by thumbtak2** [EionRobb/purple-pulsesms#6]
I login with the same information I use on the pulsesms website and the application crashes Pidgin.

**Comment by EionRobb** [comment]
Can you [get a backtrace](https://developer.pidgin.im/wiki/GetABacktrace)?

**Comment by thumbtak2** [comment]
I am an IT person, but I have never done this before. It is new to me.

**Terminal**
<img src="https://i.imgur.com/bAlGuCY.png">

**pidgin-backtrace.log**
<img src="https://i.imgur.com/KQdqBtd.png">

**Comment by EionRobb** [comment]
Looks like something strange happened with the `tee` command.

Try just `gdb pidgin` then `run`.  When it crashes, then type `bt full` and copy-paste the output of that here.

**Comment by thumbtak2** [comment]
<img src="https://i.imgur.com/72lbmu8.png">

**Comment by EionRobb** [comment]
That's weird, you managed to run `gdb` before, do you need to `apt install` it again?

**Comment by thumbtak2** [comment]
<pre><font color="#55FF55"><b>USER@debian</b></font>:<font color="#5555FF"><b>~</b></font>$ su
Password: 
root@debian:/home/USER# aot install gdb
bash: aot: command not found
root@debian:/home/USER# apt install gdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libbabeltrace1 libc6-dbg libipt2
Suggested packages:
  gdb-doc gdbserver
The following NEW packages will be installed:
  gdb libbabeltrace1 libc6-dbg libipt2
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.8 MB of archives.
After this operation, 27.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main amd64 libbabeltrace1 amd64 1.5.6-2+deb10u1 [172 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libipt2 amd64 2.0-2 [41.7 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 gdb amd64 8.2.1-2+b3 [3,133 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 libc6-dbg amd64 2.28-10 [11.5 MB]
Fetched 14.8 MB in 1s (19.1 MB/s)<font color="#AA5500">   </font>
Selecting previously unselected package libbabeltrace1:amd64.
(Reading database ... 187384 files and directories currently installed.)
Preparing to unpack .../libbabeltrace1_1.5.6-2+deb10u1_amd64.deb ...
Unpacking libbabeltrace1:amd64 (1.5.6-2+deb10u1) ...
Selecting previously unselected package libipt2.
Preparing to unpack .../libipt2_2.0-2_amd64.deb ...
Unpacking libipt2 (2.0-2) ...
Selecting previously unselected package gdb.
Preparing to unpack .../gdb_8.2.1-2+b3_amd64.deb ...
Unpacking gdb (8.2.1-2+b3) ...
Selecting previously unselected package libc6-dbg:amd64.
Preparing to unpack .../libc6-dbg_2.28-10_amd64.deb ...
Unpacking libc6-dbg:amd64 (2.28-10) ...
Setting up libc6-dbg:amd64 (2.28-10) ...
Setting up libipt2 (2.0-2) ...
Setting up libbabeltrace1:amd64 (1.5.6-2+deb10u1) ...
Setting up gdb (8.2.1-2+b3) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
root@debian:/home/USER# gdb pidgin
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type &quot;show copying&quot; and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-linux-gnu&quot;.
Type &quot;show configuration&quot; for configuration details.
For bug reporting instructions, please see:
&lt;http://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
    &lt;http://www.gnu.org/software/gdb/documentation/&gt;.

For help, type &quot;help&quot;.
Type &quot;apropos word&quot; to search for commands related to &quot;word&quot;...
Reading symbols from pidgin...(no debugging symbols found)...done.
(gdb) exit
Undefined command: &quot;exit&quot;.  Try &quot;help&quot;.
(gdb) q
root@debian:/home/USER# gdb pidgin
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type &quot;show copying&quot; and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-linux-gnu&quot;.
Type &quot;show configuration&quot; for configuration details.
For bug reporting instructions, please see:
&lt;http://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
    &lt;http://www.gnu.org/software/gdb/documentation/&gt;.

For help, type &quot;help&quot;.
Type &quot;apropos word&quot; to search for commands related to &quot;word&quot;...
Reading symbols from pidgin...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/lib/x86_64-linux-gnu/libthread_db.so.1&quot;.
Couldn&apos;t create plugins dir
[New Thread 0x7fffeff09700 (LWP 2248)]
[Detaching after fork from child process 2249]
[New Thread 0x7fffeef35700 (LWP 2252)]
[New Thread 0x7fffee734700 (LWP 2253)]
[Detaching after fork from child process 2558]

Thread 1 &quot;pidgin&quot; received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:304
304	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt full
#0  0x00007ffff6d2d71e in __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:304
#1  0x00007ffff067d369 in pulsesms_decrypt_len
    (data=&lt;optimized out&gt;, len=len@entry=0x0, psa=&lt;optimized out&gt;)
    at libpulsesms.c:103
        parts = 0x5555565a2be0
        text_len = 16
        iv_len = 93825009347904
        ciphertext = 0x0
        IV = 0x0
        buf_len = &lt;optimized out&gt;
        buf = 0x5555565a6cb0 &quot;&quot;
#2  0x00007ffff067df24 in pulsesms_decrypt
    (data=&lt;optimized out&gt;, psa=0x555555b32a30) at libpulsesms.c:127
        phone_number = 0x5555565a6d40 &quot;559-756-5708,**12105011374,904-422-1776,(504) 292-2434,1 708-926-1688,832-714-7740,(570) 257-0419,1-702-666-7544,(832) 275-3876,17089261688,8322753876,9044221776,5702570419,5042922434,17026667544,8327&quot;...
        id_matcher = &lt;optimized out&gt;
        contact = 0x555556590430
        name = 0x5555565a6c80 &quot;secret sheep&quot;
        buddy = &lt;optimized out&gt;
        psa = 0x555555b32a30
--Type &lt;RET&gt; for more, q to quit, c to continue without paging--
        len = 138733
        data = &lt;optimized out&gt;
        contacts = 0x555555ae1ae0
        i = 456
        group = 0x555555a8f2a0
#3  0x00007ffff067df24 in pulsesms_got_contacts
    (http_conn=&lt;optimized out&gt;, response=&lt;optimized out&gt;, user_data=0x555555b32a30) at libpulsesms.c:307
        phone_number = 0x5555565a6d40 &quot;559-756-5708,**12105011374,904-422-1776,(504) 292-2434,1 708-926-1688,832-714-7740,(570) 257-0419,1-702-666-7544,(832) 275-3876,17089261688,8322753876,9044221776,5702570419,5042922434,17026667544,8327&quot;...
        id_matcher = &lt;optimized out&gt;
        contact = 0x555556590430
        name = 0x5555565a6c80 &quot;secret sheep&quot;
        buddy = &lt;optimized out&gt;
        psa = 0x555555b32a30
        len = 138733
        data = &lt;optimized out&gt;
        contacts = 0x555555ae1ae0
        i = 456
        group = 0x555555a8f2a0
#4  0x00007ffff068148b in purple_http_connection_terminate (hc=0x555555be6c60)
--Type &lt;RET&gt; for more, q to quit, c to continue without paging--
    at purple2compat/http.c:1725
        __func__ = &quot;purple_http_connection_terminate&quot;
#5  0x00007ffff06837b8 in _purple_http_recv_loopbody
    (hc=hc@entry=0x555555be6c60, fd=&lt;optimized out&gt;)
    at purple2compat/http.c:1293
        redirect = &lt;optimized out&gt;
        len = &lt;optimized out&gt;
        buf = &quot;0\r\n\r\n(\017\312\337\355\035\002\000\r\n\005V\230%\036\204\027\236\350Y\340$@x\217\&quot;\346\337G\263xL\264t7\035w\376\000\062\252\352\234&lt;\225\225\t\321X\256\033\bX\356\256ԲL\201\244\037Ƞ{c\335\023\243\021\022\205-\213\214l$Q\021\377 \023^v\356fi\217\214\000\373\307\f7\000:\221ԥ\255\237\274\233\354\276\326\032Є\031c\226\343\331W\363\214|\345Ph7:\037خ\204\062\254nn\260N\307fw\316.˒\273\061\326C\024\\\360u}\300\252\275\360\200\362\265\220~\315\065:E\343\257\021\223@;}\324X\340w\363\346\234\301NSc?\264\335T|\272Q\234\303AD~Q?\025]\250\316\000qd\310&quot;...
        got_anything = &lt;optimized out&gt;
#6  0x00007ffff0683ca0 in _purple_http_recv
    (_hc=0x555555be6c60, fd=&lt;optimized out&gt;, cond=&lt;optimized out&gt;)
    at purple2compat/http.c:1304
        hc = 0x555555be6c60
#7  0x00005555555ca98e in  ()
#8  0x00007ffff70c8dd8 in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type &lt;RET&gt; for more, q to quit, c to continue without paging--
#9  0x00007ffff70c91c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff70c94c2 in g_main_loop_run ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff75928e7 in gtk_main ()
    at /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#12 0x000055555559098b in main ()
(gdb) 
</pre>

**Comment by paulsybrandy** [comment]
____________________________________________________________
So upon trying to find a reason why this was happening to me, I decided to follow your instructions and here is the output of my "bt full":

(gdb) bt full
#0  0x00007ffff6ddf7f8 in  () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff206798e in pulsesms_got_login
    (http_conn=<optimized out>, response=<optimized out>, user_data=0x555556ce9350) at libpulsesms.c:628
        psa = 0x555556ce9350
        len = 34
        data = <optimized out>
        info = 0x555556cd4720
        password = 0x555556ce7030 "ilovetexting23"
        salt2 = 0x0
        dklen = 32
        rounds = 10000
        DK = "\320~GVUU\000\000\000\000\000\000\000\000\000\000\237\355(\367\377\177\000\000\000\223\362VUU\000"
        hash = <optimized out>
#2  0x00007ffff206a56c in purple_http_connection_terminate (hc=0x555556d5eed0) at purple2compat/http.c:1725
        __func__ = "purple_http_connection_terminate"
#3  0x00007ffff206c4c8 in _purple_http_recv_loopbody (hc=hc@entry=0x555556d5eed0, fd=<optimized out>)
    at purple2compat/http.c:1293
        redirect = <optimized out>
        len = <optimized out>
        buf = "0\r\n\r\n\332\016\245\333\"\000\000\000\r\n\310IM,NU(\316\317)KU(JuN,(I\316HT\252\005\000\000\000\377\377\r\n: Mon, 29 Aug 2022 14:11:21 GMT\r\nConnection: keep-alive\r\nContent-Type: application/json; charset=utf-8\r\nVary: Accept-Encoding, Origin\r\nContent-Encoding: g"...
        got_anything = <optimized out>
#4  0x00007ffff206cb80 in _purple_http_recv (_hc=0x555556d5eed0, fd=<optimized out>, cond=<optimized out>)
    at purple2compat/http.c:1304
        hc = 0x555556d5eed0
#5  0x00005555555ce4b2 in  ()
#6  0x00007ffff728deb4 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff728e258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff728e543 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff7936b2a in gtk_main () at /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#10 0x0000555555591d7c in main ()
(gdb) 


Any assistance would be much appreciated!
